### ISSUE TITLE
No Italics

### ISSUE THREAD

**Issue by DenisValcke** [chiragpat/tomorrow-and-tomorrow-night-operator-mono-theme#1]
Hi

I installed the extension today and in all varieties of the theme I don't have italic keywords.

My config looks as follow:

```json
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "Tomorrow Night Eighties",
  "editor.fontFamily": "Operator Mono, Consolas, 'Courier New', monospace",
  "editor.fontSize": 14,
  "editor.fontLigatures": true,
  "editor.renderWhitespace": "boundary",
  "editor.minimap.enabled": false,
```

<img width="358" alt="html" src="https://user-images.githubusercontent.com/12268407/29356517-d0170e98-8274-11e7-87cc-612f99f0cb10.png">
<img width="377" alt="typescript" src="https://user-images.githubusercontent.com/12268407/29356516-d0056314-8274-11e7-8e59-a04e99b1484f.png">

**Comment by chiragpat** [comment]
Hey Denis,

Looks like you are still using the Tomorrow Night Eighties Theme instead of the Operator Mono version. Can you try changing your config to be,

`"workbench.colorTheme": "Tomorrow Night Eighties Operator Mono"`

Chirag

**Comment by DenisValcke** [comment]
Nice! 👌🏻

It was indeed conflicting with the other Tomorrow theme, uninstalling that extension and setting it specifically to what you suggested in my config solved the problem.

Thanks and nice work 👍
